[package]
name = "todoo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = "0.4.6"
tracker = "0.1"
relm4 = {version = "0.4.3", features = ["libadwaita", "macros", "tokio-rt"] }
relm4-macros = "0.4.3"
relm4-components = "0.4.0"
cascade = "1.0.0"
reqwest = { version = "0.11.10", features = ["blocking"]}
tokio = { version = "1.17.0", features = ["full"]}
serde = { version = "1.0.136", features = ["derive"]}
serde_json = "1.0"
anyhow = "1.0.56"
chrono = { version = "0.4.19", features = ["serde"] }