[package]
name = "do"
version = "0.1.2"
edition = "2021"
authors = ["Eduardo Flores <edfloreshz@gmail.com>"]
license = "GPL-2.0"
description = "Do is a rewrite of GNOME To Do in Rust and Relm4."
homepage = "https://do.edfloreshz.dev/"
documentation = "https://docs.rs/do"
repository = "https://github.com/edfloreshz/do/"
readme = "README.md"

[[bin]]
name = "todo"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = "0.4.7"
glib = "0.15.10"
relm4 = {version = "0.4.4", features = ["libadwaita", "macros", "tokio-rt"] }
relm4-components = "0.4.4"
relm4-macros = "0.4.4"
tokio = { version = "1.17.0", features = ["full"] }
serde = { version = "1.0.136", features = ["derive"]}
serde_json = "1.0"
once_cell = "1.10.0"
anyhow = "1.0.56"
cascade = "1.0.0"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
tracker = "0.1.1"
diesel = { version = "1.4.8", features = ["sqlite"] }
diesel_migrations = "1.4.0"
dotenv = "0.15.0"
dirs = "4.0.0"
chrono = "0.4.19"
libset = "0.1.1"