name: Flatpak

on:
  release:
    types: [published]
    branches: [main]
    
jobs:
  publish:
    name: "Publish to Flathub"
    runs-on: ubuntu-latest
    if: "${{ github.event_name == 'release' }}"
    env:
      FLATPAK_BUILD_PATH: flatpak_app/files/share
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-42
      options: --privileged
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build Flatpak Manifest
      uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: doable-${{ steps.setup.outputs.commitHash }}.flatpak
        manifest-path: dev.edfloreshz.Doable.json
        cache-key: flatpak-builder-${{ hashFiles('dev.edfloreshz.Doable.json') }}
        mirror-screenshots-url: https://dl.flathub.org/repo/screenshots
        branch: stable
        
    - name: Publish to Flathub
      uses: bilelmoussaoui/flatpak-github-actions/flat-manager@v4
      with:
        flat-manager-url: https://hub.flathub.org/
        repository: stable
        token: ${{ secrets.FLATHUB_TOKEN }}
